### ISSUE TITLE
[URGENT BUG NEEDS FIXING] Player::getSkinName is broken. Please fix onebone! 

### ISSUE THREAD

**Issue by MajorPlayz** [onebone/NPC#10]
`[Server] [20:25:33] [Server thread/CRITICAL]: Unhandled exception executing command 'npc create test' in npc: Call to undefined method pocketmine\Player::getSkinName() [Server] [20:25:33] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\Player::getSkinName()" (EXCEPTION) in "/NPC_v1.3.1.phar/src/onebone/npc/Main" at line 132`

I have no idea what is going on :D

Please fix this onebone as Npc will play a vital part in my server XD 
Thanks

**Comment by JellyBrick** [comment]
Now it has been fixed.
