### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Erkam246** [onebone/NPC#17]
[Server thread/CRITICAL]: "The Event 'pocketmine\event\entity\EntityTeleportEvent' cannot give to 'NPC v1.4' : Call to a member function getFolderName() on null in onebone\npc\Main" [12:14:08] [Server thread/CRITICAL]: Error: "Call to a member function getFolderName() on null" (EXCEPTION) in "/NPC-master/src/onebone/npc/Main" at line 115

**Comment by zahf22** [comment]
same here

**Comment by legoboy0215** [comment]
Which server software are you guys using?

**Comment by zahf22** [comment]
sir im using the latest genisys

**Comment by Erkam246** [comment]
I too
