### ISSUE TITLE
On 0.16 doesn't work!!!

### ISSUE THREAD

**Issue by Dhrhciebcy** [onebone/NPC#20]
In the new minecraft version (0.16.0.5), it doesn't work, probably it is not compatible. I use Genisys

**Comment by Dhrhciebcy** [comment]
Me too, also in the new version of minecraft 1.0.0 it doesn't work. I have this errors: 21:27:05 | Elywing thread:CRITICAL > Error: "Call to a member function getFolderName() on null" (EXCEPTION) in "/NPC-master/src/onebone/npc/Main" at line 92
21:27:05 | Elywing thread:CRITICAL > "Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'NPC v1.3.1': Call to a member function getFolderName() on null on onebone\npc\Main

**Comment by onebone** [comment]
You are using old version.
Try from https://jenkins.onebone.me/job/NPC/

**Comment by EndreEndi** [comment]
Onebone,. update this plugin? For 1.0

**Comment by Dhrhciebcy** [comment]
I have downloaded the new version of NPC from https://jenkins.onebone.me/job/NPC/. It now spawn the human but it's bugged. The console has this errors: 10:01:49 | Elywing thread:CRITICAL > Unhandled exception executing command 'npc create test' in npc: Call to a member function getFolderName() on null
10:01:49 | Elywing thread:CRITICAL > Error: "Call to a member function getFolderName() on null" (EXCEPTION) in "/NPC_v1.4-7a6e397a.phar/src/onebone/npc/NPC" at line 211
10:01:53 | Elywing thread:CRITICAL > "Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'NPC v1.4': Call to a member function getFolderName() on null on onebone\npc\Main
10:01:53 | Elywing thread:CRITICAL > Error: "Call to a member function getFolderName() on null" (EXCEPTION) in "/NPC_v1.4-7a6e397a.phar/src/onebone/npc/Main" at line 105
10:01:54 | Elywing thread:CRITICAL > "Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'NPC v1.4': Call to a member function getFolderName() on null on onebone\npc\Main

I use minecraft version 1.0.0

**Comment by Dhrhciebcy** [comment]
I AM SORRY: the plugin works, I have deleted the data folder and now it works!!! Thanks very much
