### ISSUE TITLE
You know Rotation?

### ISSUE THREAD

**Issue by ghost** [onebone/NPC#26]
url : https://github.com/jojoe77777/SlapperRotation

Add functionality to the NPC plugin

**Comment by onebone** [comment]
You mean this?

https://github.com/onebone/NPC/blob/master/src/onebone/npc/NPC.php#L109

**Comment by ghost** [comment]
I did not understand what you were saying.

all I'm saying is that the NPC is looking at me.

**Comment by ghost** [comment]
NPC 가 자동으로 나를 바라보게 하는 플러그인입니다.

**Comment by onebone** [comment]
So what you are saying is this.

https://github.com/onebone/NPC/blob/master/src/onebone/npc/NPC.php#L109

It is already implemented in the plugin.
