### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by tigerza117** [onebone/NPC#4]
How TO SetName NPC
id am add code
`public function setName($name){
        $this->name = $name;
        return $this->name;
    }`
to set name but name not update on set i am use setnametag player not work 
`$o = $this->getServer()->getOnlinePlayers();
 foreach ($o as $p) {
            foreach ($this->npc as $npc) {
            /*    if ($npc->getLevel()->getFolderName() === $p->getLevel()->getFolderName()) {
                    $npc->removeFrom($p);
                }*/
                $time1 = intval(time());
                $time = date("m-d-Y H:i:s", $time1);
                if($npc->getId() === 1){
                    $npc->setName($time);
                }
                if($npc->getId() === 2){
                    $npc->setName($time);
                }
                if($npc->getId() === 3){
                    $npc->setName($time);
                }
                if($npc->getId() === 4){
                    $npc->setName($time);
                }
                if($npc->getId() === 5){
                    $npc->setName($time);
                }
                if ($npc->getLevel()->getFolderName() === $p->getLevel()->getFolderName()) {
                    $npc->spawnTo($p);
                }
            }
        }`
Code this work but npc new spawn on name update it not ok

**Comment by tigerza117** [comment]
public function setNameTag($name){
        $this->setDataProperty(self::DATA_NAMETAG, self::DATA_TYPE_STRING, $name);
    }
Not Work

**Comment by onebone** [comment]
NPC doesn't extend Entity class. You have to send packet by your hand.
